### ISSUE TITLE
Creating this as documentation for anyone else who may need it

### ISSUE THREAD

**Issue by Schaka** [eritpchy/videosubfinder-cli#1]
On MacOS, brew downloads opencv 4.8.0 This leads to issues with the CLI looking for 4.0.7 files in the 4.8.0 installation folders.
You can find the last version of 4.7.0 here: https://raw.githubusercontent.com/Homebrew/homebrew-core/1f177f4241acf66504cb08fa0fe29a32793660ec/Formula/opencv.rb

Download it to a folder as `opencv.rb`, then execute
```
brew install opencv.rb
rm opencv.rb
```

For ffmpeg, make sure to get 5.1.3 via
```
brew uninstall ffmpeg
brew install ffmpeg@5.1.3
```

**Comment by eritpchy** [comment]
Stuck during processing?

**Comment by Schaka** [comment]
```
VideoSubFinderCli -h
dyld[13232]: Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.59.dylib
  Referenced from: <0EAAD0C1-BB4A-3F2B-BADB-4E6ACF8E5F57> /Users/jonas.taenzer/Documents/ytl-dlp/VideoSubFinderCli
  Reason: tried: '/usr/local/opt/ffmpeg/lib/libavcodec.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ffmpeg/lib/libavcodec.59.dylib' (no such file), '/usr/local/opt/ffmpeg/lib/libavcodec.59.dylib' (no such file), '/usr/local/lib/libavcodec.59.dylib' (no such file), '/usr/lib/libavcodec.59.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/ffmpeg/6.0_1/lib/libavcodec.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/ffmpeg/6.0_1/lib/libavcodec.59.dylib' (no such file), '/usr/local/Cellar/ffmpeg/6.0_1/lib/libavcodec.59.dylib' (no such file), '/usr/local/lib/libavcodec.59.dylib' (no such file), '/usr/lib/libavcodec.59.dylib' (no such file, not in dyld cache)
zsh: abort      VideoSubFinderCli -h
```
The file in that directory is ```libavcodec.60.dylib```.

Similar to this, except looking for opencv. I'm gonna grab ffmpeg 5.9 and post the info here too so you can add it to the readme if needed.

**Comment by eritpchy** [comment]
This is caused by brew upgrading ffmpeg to version 6.0 and opencv 4.8.0. Under normal circumstances, the program needs to be recompiled. I will update this project later when I have free time.

**Comment by eritpchy** [comment]
fixed in [v5.70.1](https://github.com/eritpchy/videosubfinder-cli/releases/tag/5.70.1-ci)
You can try the static build version, it does not require other dynamic libraries.
[videosubfinder-cli-cpu-static-linux-x64.tar.gz](https://github.com/eritpchy/videosubfinder-cli/releases/download/5.70.1-ci/videosubfinder-cli-cpu-static-linux-x64.tar.gz)

**Comment by Schaka** [comment]
I'm on MacOS, where I decided to upgrade the dependencies again and still get this error afterwards:
```
dyld[4429]: Library not loaded: /usr/local/opt/opencv/lib/libopencv_videoio.407.dylib
  Referenced from: <0EAAD0C1-BB4A-3F2B-BADB-4E6ACF8E5F57> /Users/jonas.taenzer/Documents/ytl-dlp/VideoSubFinderCli
  Reason: tried: '/usr/local/opt/opencv/lib/libopencv_videoio.407.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/opencv/lib/libopencv_videoio.407.dylib' (no such file), '/usr/local/opt/opencv/lib/libopencv_videoio.407.dylib' (no such file), '/usr/local/lib/libopencv_videoio.407.dylib' (no such file), '/usr/lib/libopencv_videoio.407.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/opencv/4.8.0_6/lib/libopencv_videoio.407.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/opencv/4.8.0_6/lib/libopencv_videoio.407.dylib' (no such file), '/usr/local/Cellar/opencv/4.8.0_6/lib/libopencv_videoio.407.dylib' (no such file), '/usr/local/lib/libopencv_videoio.407.dylib' (no such file), '/usr/lib/libopencv_videoio.407.dylib' (no such file, not in dyld cache)
zsh: abort      VideoSubFinderCli -h
```

I appreciate you fixing up the Linux version. I've since done the work I needed to do on another machine.

**Comment by eritpchy** [comment]
Sorry, I forgot you are macOS system, try [videosubfinder-cli-v5.70.1-darwin-x64.tar.gz](https://github.com/eritpchy/videosubfinder-cli/releases/download/5.70.1-ci/videosubfinder-cli-darwin-x64.tar.gz) 
run ./VideoSubFinderCli.run 

The relevant dynamic libraries are all in the lib directory.
